vich_uploader:
    db_driver: orm

    mappings:
        estudante_foto:
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true
            uri_prefix:          /assets/img/estudante
            upload_destination: '%kernel.project_dir%/public/assets/img/estudante'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
